### ISSUE TITLE
GetCoverage method in dev branch appears to returns 100 when there is no coverage.

### ISSUE THREAD

**Issue by jrossignol** [KSPModStewards/SCANsat#108]
Can you explain why the getCoveragePercentage method returns 100 when the coverage is 0?  From SCANutil.cs in the dev branch:

```
    internal static double getCoveragePercentage(SCANdata data, SCANtype type )
    {
        if (data == null)
            return 0;
        double cov = 0d;
        if (type == SCANtype.Nothing)
            type = SCANtype.AltimetryLoRes | SCANtype.AltimetryHiRes | SCANtype.Biome | SCANtype.Anomaly;          
        cov = data.getCoverage (type);
        if (cov <= 0)
            cov = 100;
        else
            cov = Math.Min (99.9d , 100 - cov * 100d / (360d * 180d * countBits((int)type)));
        return cov;
    }
```

I suspect that is what is giving us some issues in Contract Configurator where the SCANsat coverage parameters get met unexpectedly.  See the report from @DBT85 in the Contract Configurator thread starting [here](http://forum.kerbalspaceprogram.com/threads/101604-0-90-Contract-Configurator-v0-5-5-2015-01-13?p=1672596&viewfull=1#post1672596).

**Comment by DMagic1** [comment]
It's that if (cov<=0) cov = 100; line that's causing the issue. 

The coverage amount for each scanner type is stored in an array in SCANdata. It gets initialized to zero, which results in showing 100% coverage because of the way the amount is inverted. 

Because updating this int[] for each planet constantly is very slow only one planet is updated at a time. This means that it takes a while for each planet to get updated after loading.

The best solution might be to load each SCANdata's coverage array when it initially loads. That way the amounts will be returned correctly. Or maybe just initialize the int[] with all values at the max amount.

**Comment by jrossignol** [comment]
I think initializing to fully uncovered would be sufficient for Contract Configurator's needs.  It leaves the possibility that the contract parameter window briefly shows 0% coverage instead of x%....  but that's a minor display issue I can live with.
