### ISSUE TITLE
could we have other palettes for the biome map as well?

### ISSUE THREAD

**Issue by Schnobs** [KSPModStewards/SCANsat#112]
Sometimes, I wish I could switch it to garish high-contrast colors similar to the F12 view in the game. If it can be done, I fail to see how -- palette control only seems to affect altitude maps. The perfect solution would let me assign a color to every biome, but for most practical purposes, one or two random selections of bright colors would suffice.

And while I'm at it, would you be willing to add a simple blue->green->red palette, too? It may not be suitable for the colorblind, but I'm capable of seeing the full spectrum and would like to have it as an option.

**Comment by DMagic1** [comment]
Yes, improving the biome maps and maybe making the color scheme adjustable is a good idea and something that is planned.

Also, making the garish biome maps is very simple, like one little line change is all that's necessary. Actually, I think that they look even better than the stock overlays because these retain those white border lines. This can probably be added as a simple toggle in the next update. 

![](http://i.imgur.com/rv6Busk.png)
