### ISSUE TITLE
Half science for Jool and Sun

### ISSUE THREAD

**Issue by Amorymeltzer** [KSPModStewards/SCANsat#125]
While largely useless, you can in fact receive science from a given scan for Jool and the Sun.  The scans, though, are worth half the science data one might expect.  `InSpaceHigh` for Jool and the Sun are 6 and 2, respectively, but the cap value of the scans are 60 and 20, not 120 and 40.  Is this intentional since there's no surface, therefore there should be reduced science, or just a holdover from the no biomes era?  If it's intentional, I think it should be reduced even lower - a factor of five, perhaps - if not brought down all the way to zero.

Apologies if this would be better suited for the forum.

**Comment by DMagic1** [comment]
Yes this is intentional. Originally there was intended to be 0 science for planets without terrain or biomes, but a bug allowed science to still be gained from planets without biomes.

Since everyone assumed that the opposite was a bug, that you weren't able to get science from planets without terrain, there was a lot of complaining about not getting science from terrain scans of Jool (I'm not sure that I've actually seen anyone get into a low enough orbit around the sun without cheating, but I did it once, just to be sure). 

I changed it so that you could get science everywhere. The half science amount seemed like a reasonable compromise.

**Comment by Amorymeltzer** [comment]
Gotcha, thanks!
