### ISSUE TITLE
Science based on scan location, not transmit location

### ISSUE THREAD

**Issue by DidaskalosDD** [KSPModStewards/SCANsat#178]
After a biome scan of Mun (worth 40 points) I brought the scanner back to Kerbin orbit to transmit...and it was sent as a Kerbin scan worth only 30 points.  Not sure if this is a SCANsat issue, but there it is.

**Comment by DMagic1** [comment]
Wow, I'm surprised this has never come up before. But you're right, when you transmit it recalculates the science value using your current location. I think the reason for this is something about making sure the science data is up to date, in case you've scanned more since collecting the data. But that doesn't really seem useful, I'll change this for the next update.

**Comment by DidaskalosDD** [comment]
Yeah, I searched the issues to make sure.  The reason it came up was I
didn't have enough charge to send it, so I brought it back to Kerbin so I
could mount another battery on it in LKO.  The mission was successful, then
I saw the 10 science loss.  I sent a rescue mission to Minmus to fix the
same issue and get full science and it worked.  Anyway, there it is.
Thanks for taking a look at it.
