### ISSUE TITLE
Configurable color scale for the slope display

### ISSUE THREAD

**Issue by jd284** [KSPModStewards/SCANsat#196]
Currently the range of slopes from "completely flat" to "dangerously steep" are all indistinguishable shades of green and do not help at all in finding a flat spot to land. One has to mouse-over every pixel and hope to find one with acceptable slope.

So please let us configure the range of slopes for the "low" and "high" color scales, or change it that the threshold between "low" and "high" is closer to 5 degrees or so. A configuration file setting would be fine as well (as long as it can be patched via a custom MM cfg).

Adding a single slider for the threshold instead would be very helpful as well.

**Comment by DMagic1** [comment]
The slope map is terrible not because of the color scheme or how it is displayed, but because it isn't measuring anything resembling actual slope. 

What it actually does is compare the elevation at the current pixel to a few nearby pixels (but really only selects one of those pixels to make the comparison), then makes a somewhat arbitrary decision to display the final result between one of the two color pairs.

It needs to be improved, though there isn't much that can be done without asking KSP for more terrain data, which is very slow. It also becomes less useful the more you zoom in, as the algorithm tends to flatten out differences at higher zoom levels. For the current setup a slider to adjust the threshold for the two color pairs should be simple.

**Comment by jd284** [comment]
I understand the limited accuracy of the slope map, but it is still useful for finding flat-ish regions in a given biome. It's just tedious right now because of the pixel hunting, so the slider you mentioned would help a lot.
