### ISSUE TITLE
Screen fonts changing (un readable blurs)

### ISSUE THREAD

**Issue by Agnemon** [KSPModStewards/SCANsat#247]
nVidia 1080 Graphics
32" 4k Monitor (1920 x 1080)
Scansat 16.9
KSP 1.2 Win64

KSP works fine until I go into scansat. Once I leave Scansat the screen fonts (Avacado green) are blurred and unreadable, (there is a bar code font that is all rectangular blocks, looks like that). Mechjeb fonts are fine as are the orbit mark fonts (PE AP etc) once the font has changed the only way to restore it fully is to restart KSP.

Amp Year 1.4.1
Ashpalt Tiles 1.2
Chatterer 0.9.91
Editor Extensions Redux 3.3.3
EVA Transfer 5.0
Etraplanetery Launchpads 5.5.1
Flexible Docking 4.0
KAS 0.6.0
Kerbal Planetary Base Systems 1.3
Kerbal Stats 2.1
KIS 1.3.0
Mechjeb 2.5.9.0 (642)
Modular Rocket Systems 1.13.0
Module Manager 2.7.1
Portrait Stats 12.0
RCS BuildAid 0.9
Scansat 16.9
TweakScale 2.3.1
UbioWeldContinued 2.3.4

**Comment by MaceWe** [comment]
The screwed up fonts switch back and forth if you toggle "Draw Overlay". I could not pin down this issue to any mod conflict. At the moment I blame DX11 on that.

**Comment by DMagic1** [comment]
Do either of you have full log files?

**Comment by Agnemon** [comment]
As of right now, no  will see if I can recreate the problem tomorrow.  Haven’t had the problem today, which is strange, it was consistent.

**Comment by Agnemon** [comment]
I haven't been able to replicate the problem how ever, the following mods from the original list (4 posts up) have been upgraded since then so they may have fixed the problem

Kerbal Planetary Base Systems 1.3 >> 1.3.2
Modular Rocket Systems 1.13.0 >> 1.13.1
Scansat 16.9 >> 16.10

Will keep trying

**Comment by Jaidan** [comment]
I have this issue 100% and easily reproduced, though I run a reasonably large number of  mods and I haven't tried a bare install yet due to time constraints.

The steps to reproduce:
Enable an overlay
Without removing the overlay do something that causes the overlay to be cleared (switching vessels is the easiest)
Rotate the camera so that the sun is at your back
Mouse over any vessel, pe, ap, etc.

To temporarily resolve it:
Toggle the overlay.

**Comment by DMagic1** [comment]
I see it. This isn't the first time the overlays have caused strange problems like this.

**Comment by Ruedii** [comment]
I don't see anything here that would cause this.  I would suspect it's a driver or a hardware issue. 

I know some 4K monitors actually don't have full pixel triads for each pixel and instead use interpolating.  This can cause blurry fonts in applications with small fonts.  Generally they have between a 2:3 ratio and a 1:3 ration of physical pixels to virtual pixels.  However, some can go far higher by utilizing the subpixel intersection as the rendering point, instead of the subpixel points.  (See Wikipedia's article on Subpixel rendering for details.)  The same goes for tablets and such.

Likewise, if you have super-scaler rendering enabled on the nVidia cards, this further reduces physcial DPI to Virtual DPI ratio.

**Comment by DMagic1** [comment]
Blurry text probably isn't the right term for it, and it isn't an issue of the pixels on a monitor.

This is somehow related to how Unity renders the TextMeshPro text (old GUI text isn't affected), which is somehow affected by turning on the resource texture. Activating the resource overlay texture sets the overlay texture for a planet's shader (which has several textures: visible, normal map, and overlay), turning it off just destroys that texture. For whatever reason not destroying that texture before a scene switch (which SCANsat tries to do, but apparently doesn't get to it fast enough) does some very weird things.

It's somewhat critical to get this fixed for the next version (aside from the obvious reasons) since SCANsat will be using TMP text and it will be much harder to toggle the overlay on and off again with the text blurred out.


![](http://i.imgur.com/kDvVeEM.png)

**Comment by DMagic1** [comment]
I think I've got this one. It looks like it is related to a problem with the scaled space component of the celestial body; it doesn't seem to like forcing the removal of the overlay map right as the scene is about to switch.

It should be fixed in the next pre-release version. 

Current pre-release versions also don't seem to show this problem, but that is for a slightly different reason and they may have other problems related to switching scenes with an overlay on.

**Comment by Agnemon** [comment]
One thing I have noticed recently (upgraded computer) is it seems that a call to the text routine is setting the background colour to the foreground colour and then another call (duplicate code?) is resetting it back.
My old system was quite slow and couldn't update the display fast enough, the new one (NVidia 1080) is a lot faster and shows the flicker quite clearly.

**Comment by DMagic1** [comment]
Fixed in version 18. Hopefully...

**Comment by Ruedii** [comment]
The fonts appear on the soft side on my system, but are not blurry or hard
to read anymore.  I would say this is fixed.
