### ISSUE TITLE
Gets stuck on KSP startup

### ISSUE THREAD

**Issue by AssassinAgent** [KSPModStewards/SCANsat#269]
I'm a noob when it comes to modding KSP and I have no clue what has gone wrong...
The loading bar gets stuck at SCANsat/Parts/SAR/SAR/SCANsat_Scanner2
[output_log.txt](https://github.com/S-C-A-N/SCANsat/files/957575/output_log.txt)
KSP version is 1.2.2 and scansat version is 17.5

**Comment by DMagic1** [comment]
It looks like it could be getting stuck on the next part.

The log file mentions a part upgrade problem:

NullReferenceException: Object reference not set to an instance of an object
  at PartUpgradeHandler.LinkUpgrades () [0x00000] in <filename unknown>:0 
  at PartLoader+<CompileAll>c__Iterator61.MoveNext () [0x00000] in <filename unknown>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
 
But it happens after all of the SCANsat parts have been loaded and processed. So it could be unrelated, since SCANsat doesn't use any part upgrades.

The log doesn't make any mention of which part specifically is causing the problem, but they should be loaded alphabetically from the GameData folder. So check whatever comes after SCANsat and see if there is something with part upgrades (part upgrade configs have UPGRADES nodes embedded in one or more of the MODULE nodes).

**Comment by AssassinAgent** [comment]
Thanks for the help but I've already solved that problem. It took me some
luck, lots of trial and error 6 more hours digging trough the KSP and mod
files. But hey, that is just the funniest part of using mods :)
