### ISSUE TITLE
Big map broken: Window is empty, cannot be moved [IndexOutOfRangeException]

### ISSUE THREAD

**Issue by RalfJung** [KSPModStewards/SCANsat#270]
After completing a scan of Eeloo, I noticed that the big map is now broken. It is all empty except for all controls stacked on top of each other in the top-left corner. The window cannot be moved either.

KSP.log shows this error over and over:
```
[EXC 17:18:13.828] IndexOutOfRangeException: Array index is out of range.
	SCANsat.SCAN_Map.SCANmap.terrainElevation (Double Lon, Double Lat, Int32 w, Int32 h, System.Single[,] heightMap, Boolean c, SCANsat.SCAN_Data.SCANdata Data, System.Int32& Scheme, Boolean exporting)
	SCANsat.SCAN_Map.SCANmap.getPartialMap ()
	SCANsat.SCAN_UI.SCANBigMap.mapDraw (Int32 id)
	SCANsat.SCAN_UI.SCANBigMap.DrawWindow (Int32 id)
	SCANsat.SCAN_Platform.SCAN_MBW.DrawWindowInternal (Int32 id)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
```

Is there anything I can do to use SCANsat again?

EDIT: This is KSP 1.2.2., SCANsat 16.11.

**Comment by DMagic1** [comment]
Do you happen to know what the map size is in pixels?

See what happens if you resize the map. You can do this by opening the big map, then opening the settings menu, then settings a value in the Map Width text box and pressing the button.

There are some map sizes that cause this bug due to floating point errors (a map width of 1400 was triggering it for me). I think I fixed the problem in the latest dev versions.

**Comment by RalfJung** [comment]
Ah indeed, setting a different width fixed it. :)  The "bad" width was 772.

>  I think I fixed the problem in the latest dev versions.

I did not yet dare trying them because the changelog says I cannot downgrade again if something breaks...

**Comment by DMagic1** [comment]
Fixed in version 18.
