### ISSUE TITLE
Slope map very not helpful

### ISSUE THREAD

**Issue by mathuin** [KSPModStewards/SCANsat#305]
First, I can't differentiate two of the three colors on the slope map -- the left two look very similar.

Second, when I change the colors to colors I can tell apart, the results are effectively useless.

I am looking at a region on Minmus which has been scanned by SAR to have a range of slopes from 0.1 degrees to 21.0 degrees.  I have the default slope cut-off of 1.0.  It is uniform in color, even after I change the low slope color to white.  When I look at the whole of Minmus with this setting, the entire map is white except for some yellowish stuff in places -- no orange which is the high end.

There is also no legend, so even if I could tell what color something was, I wouldn't know what that color represented, without mousing over the entire map, which is what I am doing already.

This map would be useful if:
 * It had a legend, like the altimeter map, showing which colors represent which altitudes
 * The actual breakeven value was something I could set that mattered and that made a visual difference
 * (Optionally) The default colors were Blue Yellow Red or something like that instead of Yellow-Green Green-Yellow Orange, but that might just be me and at least I can fix that.

**Comment by DMagic1** [comment]
Basically you're right, the slope map isn't very useful. 

This is for several reasons, the biggest being that it isn't really measuring slope, just an approximation of it over a very wide area. This is why there is no legend, because the colors don't really correspond to meaningful slope values. 

The other slope measurements made by SCANsat are entirely different and use a very localized method of determining the slope of a 5m area on the surface, so when you mouse over the map you're really getting the slope at only the very center of the pixel. Making this type of measurement to generate the slope map isn't really practical because of how much math of the terrain data is involved. 

And making more accurate slope calculations wouldn't be all that helpful because the area represented by each pixel on the big map is simply too big. Even for a 4000 * 2000 pixel map of Minmus each pixel represents almost 200m at the equator, for Kerbin it's almost 2km. That kind of resolution doesn't help much when you are trying to find a flat place to land or put a base.

The only real way to make the slope map useful is to open the zoom map and zoom in very far. And this is also the only place where changing the slope cutoff value makes a noticeable difference. But really, when you zoom in that far the altimetry map is just as useful for finding a flat spot. The altimetry colors are based on the local min and max terrain heights for the zoom map, so the full range of colors is always represented.

I would have removed the slope map a long time ago if I didn't think people would complain too much. But as it is I don't think there is much use in spending any time trying to improve an already fairly useless aspect.

**Comment by mathuin** [comment]
I'd be 100% behind removing the slope map from the big map.  I understand that you can't really calculate and/or interpolate an actual slope value for every pixel at that level and that even if you could it wouldn't be useful for landing.  It might be useful for the small map but now that I know that the altimetry map color scale is dynamic I will try it on high zoom.  If that works, then I'd be totes fine with that map leaving entirely. :-)

I am now wondering if the slope information is available to other mods.  "Find me a circle of X radius with a slope not exceeding Y degrees close to Z position" would be very very handy for landing autopilots.  Does such a thing exist?

**Comment by DMagic1** [comment]
It seems I spoke too soon. The problem was that I wasn't taking the map scale into account, so zooming in just flattened out the image. Fixing this also improves the big map when you stretch it out a lot.

This is near the KSC with the slope cutoff at 0.2:
![](https://i.imgur.com/JMIwTZD.png)

This is on Minmus near a flat area:
![](https://i.imgur.com/evw3Yku.png)

And sometimes these weird artifacts become visible when you zoom in really far, I'll need to go to the Mun to see if the surface actually reflects this map:
![](https://i.imgur.com/Fhux6Ty.png)

**Comment by DMagic1** [comment]
Version 18.2 is out, and the slope map is probably about as useful as it will ever be.
