### ISSUE TITLE
Adjustable ground track color scheme

### ISSUE THREAD

**Issue by DMagic1** [KSPModStewards/SCANsat#347]
Allow customization of the map-view ground track scanning visualization. This is probably best accomplished by defining a color for each scan type that can be added to the SCANresource.cfg.

**Comment by Tonas1997** [comment]
Thanks for the positive reception to my idea :D

Are shaped beams possible as well?

**Comment by DMagic1** [comment]
What do you mean by shape? Some kind of 3D visualization, rather than the simple colored triangle that is used now? That might be more trouble to handle. 

Colors are relatively easy because it is easy to mix colors for scanners of different types. Mixing shapes wouldn't really be possible, so for any vessel with more than one scanner you would only be able to use one shape.

It also makes actually drawing the visualization on screen a lot more trouble, as this is all done by manually defining primitive shapes on the screen.

**Comment by Tonas1997** [comment]
Yeah, I meant different beam shapes for different sensors. Instead of "sweeping" the surface in a line, some sensors could do so with a conical beam, or a squared one. Like this,

![SCANSat](https://user-images.githubusercontent.com/43859708/63211111-d6cab580-c0ea-11e9-8aa5-e3240d91a6dc.png)

with the first figure representing how the beams currently work.

But yeah, as you mentioned it might not be doable.
