### ISSUE TITLE
Orbital Overlays don't show in career mode. Intended behavior?

### ISSUE THREAD

**Issue by Schmitt-Florian** [KSPModStewards/SCANsat#369]
Problem: 
Orbital Overlays don't show in career mode until Tracking Station upgraded to Lv. 2.
While it seems likely that this is the intended behavior, there was no mention of it in the Wiki, Readme or KSPedia.
This led me to believe I have encountered a bug and spending quite some time inventigating it.

Suggestion:
If this is the intended behavior, update Wiki, Readme and KSPedia to let players know.

KSP: 
1.8.1.2694 Windows 64bit

Mods installed:
ScanSat v19.3 prerelease 
Module Manager 4.1.3

Reproduction steps:

Have Tracking Station Lv. 1, Build a simple craft, Bring it into Orbit, Open Big ScanSat map

**Comment by FalcoGer** [comment]
Ah, I was wondering why I didn't get the orbits on the map.

**Comment by DMagic1** [comment]
The KSPedia entry has been updated to reflect this.

I think this is a technical limitation for displaying the orbit without upgrading the tracking station. KSP doesn't active the orbit object for a vessel until the tracking station is upgraded, so that information is no longer available without calculating it myself.
