### ISSUE TITLE
investigate inconsistent Analyze Data on Jool

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#44]
**acc** reports:
- orbiting Jool
  - with Multispectral, if you click **Analyze Data** with less than 30% coverage you get
    - science results box with 0 points
  - with RADAR, if you click **Analyze Data** with less than 30% coverage you get
    - no science results box

It is not known if this is a bug in general, or just for the < 30% case.

**Comment by DMagic1** [comment]
Currently the program looks for a pqs controller and if it doesn't find it (Jool and the Sun) will return null science data for altimetry scans. It is _supposed_ to do the same thing with empty biome maps, but it's actually checking the wrong thing, so people can get science for scanning a planet with no biomes.

So I think there are three options:
- Leave it as it is (people complain about this all the time, so this probably isn't a good option)
- Remove the check on the pqs controller (and the faulty biome check) and return science for all maps scans, regardless of what the map actually looks like
- Fix the faulty biome check and only return science when you get a usable map

It's not complicated to implement either of these two changes. Since no one actually realizes that the bug is in the biome science return, not the altimetry return, I think we should go with the second option and remove the pqs controller check.
