### ISSUE TITLE
Flags don't show up on map view

### ISSUE THREAD

**Issue by tophcodes** [KSPModStewards/SCANsat#53]
Toggling the flags button on the big map doesn't appear to work. Irrespective of which mode I'm in, flags don't show up on the map view.

Flags are definitely useful if I want to find a good landing spot near my previous missions.

I have tried this on mun and minmus, and attached an image (not) showing flags on mun.
![screenshot16](https://cloud.githubusercontent.com/assets/3678770/3282101/ba77fa30-f4d7-11e3-9b31-8d300546325a.png)

**Comment by DMagic1** [comment]
The version you are using is woefully out-of-date. Check out the [latest release](http://forum.kerbalspaceprogram.com/threads/80369-0-23-5-SCANsat-v6-0-Real-Scanning-Real-Science-at-Warp-Speed%21-May-17) on the forums or check the release section of the GitHub page.

That issues was caused by the update to KSP 0.23.5 and has been fixed, along with numerous other improvements.
