### ISSUE TITLE
version numbers do not work in Linux

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#55]
For both the version number in the top of Small Map, and the version number at the bottom of the Big Map, I see only "V".

**Comment by DMagic1** [comment]
I'm guessing that the method I'm using doesn't like Linux, I'll see about switching to the method that KSP APIExtensions [uses](https://github.com/Swamp-Ig/KSPAPIExtensions/blob/master/Source/Utils/SystemUtils.cs#L127-L141).

If the method I'm using is a problem then it might also be a problem for ModStatistics, since they use basically the same method for getting the information version, which is what is displayed in-game.

**Comment by technogeeky** [comment]
Please try in Windows and let me know if this fix is sufficient.

There are some curious aspects to this:
1. I have no clue why they would be different in Windows/Linux anyway.
2. From [here](http://stackoverflow.com/questions/1745691/linq-when-to-use-singleordefault-vs-firstordefault-with-filtering-criteria), it's clear that we shouldn't be using either `FirstOrDefault` or `SingleOrDefault`. The reasoning:
   1. `FirstOrDefault` only returns 1 result and never throws an exception, but we check to see if `assemblyList.count` is greater than 0 (it can only be 0 or 1).
   2. `SingleOrDefault` would thrown an exception there is more than one result in the query, and we again do the same check.
   3. I'm not sure that checking for null will ever be true, because both methods return whatever the hell a **default** assembly is. This is the real source of this bug and #56.
3. Evidently my IDE (MonoDevelop) does not support Linq very well, because I don't get auto-complete or type inference from Linq expressions.

Anyway, if this fixes this for now, just close it.

This kind of utility work should be rolled into some plugin framework (mine, perhaps).

**Comment by DMagic1** [comment]
It works fine on Windows.

I think FirstOrDefault is ok because it's only checking the First assembly that matches the provide name string (though checking for multiple copies of an assembly might also be a good idea).

AssemblyLoader.loadedAssemblies will always have multiple assemblies in the list, so FirstOrDefault/SingleOrDefault will never return a "default" assembly. It just won't find the assembly of the name we're searching for in some cases.

But SingleOrDefault might presumably cause problems if you have more than one .dll of a given name loaded by KSP. That might be causing your issue if you have multiple SCANsat.dlls hiding in some debug or release folder in GameData. So FirstOrDefault seems to get around that issue.

I'm curious what your debug log looks like at the mainmenu. It should be outputting something like: 

[Log]: [SCANlogger] Assembly: RasterPropMonitor found; Version: 0.16.5223.32097; Informational Version: 0.16.5223.32097; Location: JSI/RasterPropMonitor/Plugins

for all of the assemblies in the list I made that are loaded (also note the / in the url location; that should be correct for Unix too right? Maybe this is also an issue of multiple SCANsat.dlls). If there were default assemblies being added to the list they should show up with whatever name and version values apply. For instance, I don't have MechJeb2 or MechJebRPM, and there are no entries for those two in the KSP.log.

This might be moot though, as these methods are pretty much all included in [KSP API Extensions](https://github.com/Swamp-Ig/KSPAPIExtensions), which we might just want to add to SCANsat.

**Comment by DMagic1** [comment]
This might be a better solution: eb45ce1888cc89c7ca20887a178f520c564ddaee

In effect it checks for duplicates of an assembly, if it finds them then it just goes with the first loaded assembly (I assume that's the order it checks them) and prints a warning message.

I don't think that multiple copies of SCANsat are harmful, since it's all controlled through PartModules and the ScenarioModule, which can handle multiple assemblies. But some of the others, like SCANsatKethane will have issues.

**Comment by technogeeky** [comment]
When I was getting either error (ie, when compiled with SingleOrDefault), I had **no** output of that sort.

**Comment by DMagic1** [comment]
Fixed with 736995a66ba61da6e00b5f12b1ee59e9395cb1d4 and 5994e3eaa42abc9bff1dc242efadbc8f5edaa3bc

**Comment by technogeeky** [comment]
@DMagic1: This actually needs to be re-opened, as we confirmed yesterday
