### ISSUE TITLE
Using low altimetry data in instrument label

### ISSUE THREAD

**Issue by MarkoHess** [KSPModStewards/SCANsat#64]
I'm missing the instrument to use the early RADAR scan with their low res altimetry scan for my early landings.
Can we just display the remaining ~500 m in the instruments box instead of "NO DATA", if we have a lowres altimetry scan of our current position?

**Comment by technogeeky** [comment]
I can discern that you are talking about:
- Instruments window
- RADAR scanner (as opposed to SAR, or Multi)

But what do you mean that you are missing the instrument?
And what do you mean "display the remaining ~ 500m"?

I now guess:
- You previously got a RADAR scan of an area.
- You are now, with a different vessel, attempting a landing at the same area.
- But this vessel does not have a RADAR scanner attached.
- Therefore, the Instruments window displays **NO DATA**.
- You are using the Instruments window as an indicator of altitude (instead of some other plugin, or some native KSP method).

I guess this could be changed, but I think the original intention of the Instruments window was to read out all of the current active sensors. 

Note, that as a workaround, both the small map:

![here](http://i.imgur.com/uVP6Ujs.gif)

And the Big Map:

![here](http://i.imgur.com/JJEmDzI.png)

Display the altitude and terrain height (compared to sea level) respectively. So if you're landing and what a sense of your altitude, you can use the small map.

Also: If you don't have a sensor on-board a vessel and you wish to add it (even retroactively), you can simply use one of the modulemanager recipes to add them.

**Comment by MarkoHess** [comment]
You guessed almost right.
  • I made a RADAR scan of an area
  • I'm now, with a different vessel, attempting a landing at the same area.
  • This vessel does not have a RADAR scanner attached, but as it seems it doesn't matter. Although with a RADAR scanner i don't get the approximately altitude in the instruments window.

The way i used it in former days was to use the big map and use the approximately terrain height. So i had a relative idea, when to stop my descent and start my engines.

What irritated me since the beginning of scansat was, why there is an exact Terrain height displayed even though i have no high Resolution map of my area or the correct SAR Altimetry Sensor onboard:

![687474703a2f2f692e696d6775722e636f6d2f30416244774b4c2e676966](https://cloud.githubusercontent.com/assets/5456571/3654658/773ba952-116e-11e4-98bb-4a184382f466.gif)

In my opinion it doesn't feel right.
It would feel also right, if it is the height to sea level, that's already known for all ksp players and displayed at the top of the Screen. (like scanner 6 ( -13.6, -51.3, 253.035.3m asl (above sea Level))

It makes it pointless in career mode to RADAR scan a celestial body. When you want to land afterwards and make some more science, you can't use the scan data directly. At the big window you have to use your mouse to get the Terrain height at your position and at the picture above you just read the exact meters.

After a SAR Altimetry Sensor scan i can see the recorded data without the SAR altimetry sensor onboard only with my maptraq on my craft and see the recorded data inside the instruments window.

You know what i mean?
Don't you think this was the way it should be?

PS: when you go to sea with a gps device, you can normaly see, how deep the water is at your position without measuring the actual sea depth just by using the map someone else made. That's why i opened the issue.

**Comment by technogeeky** [comment]
I do see what you mean. Originally, I thought you were complaining that you couldn't see such data. Now I see that you think that it's objectionable to have the (altitude, in particular) status information on the Small Map because it is more accurate than the RADAR data itself.

There is a bit of a disconnect, because the RADAR map tells you the terrain height at every location (and not just the location you currently have a craft).

Nevertheless, I think we should discuss this.

The proposals thus are:
- [ ] Remove the altitude indicator on the Small Map.
- [ ] Make the altitude indicator on the Small Map approximate.
- [ ] Make the altitude indicator on the Small Map approximate, except when there is an **active** **SAR** sensor on board.
- [ ] Edit other suggestions into here this spot.

**Comment by MOARdV** [comment]
Is that number reporting altitude, or height above ground?  If it's altitude (same as the KSP altimeter), then I'd argue it's not objectionable, although maybe it doesn't need sub-meter accuracy.  If it's ground height, then I agree it's a problem.

One way to deal with it (either way) is to round to the nearest km, or display to the nearest meter when below 1km.  One could go a step farther and have it display only 2-3 significant digits of precision, regardless of the exact value, but that might be overkill.

**Comment by DMagic1** [comment]
It's reporting Vessel.heightFromTerrain(). How accurate this value is, I'm not sure, there was quite a bit of discussion on the relative accuracy of the various altitude functions a while back. 

Regardless, this could probably use some fixing along with everything else about the UI.

**Comment by MarkoHess** [comment]
I would go with "Make the altitude indicator on the Small Map approximate, except when there is an active SAR sensor on board.".
But normally an approximately altitude should be enough for the position of every satellite on the small map.
