### ISSUE TITLE
Prepare for v8 release

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#70]
This is an issue to record any changes that need to be made to clean up before releasing v8.
- [ ] screenshots
- [x] docs
- [x] source code
- [x] build environment
- [ ] testing
- [x] 1st post updating
- [x] album updating

**Comment by DMagic1** [comment]
I'll check over everything more tonight, but I think it's mostly ready. There is one outstanding issue that I can think of in the code, making sure the science collection works correctly, but otherwise I think it's at least as stable as v6.1.

The static images are probably ok, maybe some of the resource overlay images could be cropped. I think we need a better tutorial for using resource overlays, something showing scanner activation at least, to indicate that there are specific parts needed for it to work. One added album for all of that should be ok for the forum post.

I've been coming up with a change log from v6.1, so that will need to be added to the first post. That and the docs will need to be updated to reflect those changes: deprecated MapTraq, background scanning, resources, etc... Also, the included readme doesn't match the online docs in some cases; it still lists out-of-date parts.

Your latest commits on the build environment: 84b0a1c1a6e1396a5aceb46ed2926b6da36e2e28 are a little off I think, the output folder should be /SCANsat/Plugins not /SCANsat.

**Comment by technogeeky** [comment]
Last, first:

> Your latest commits on the build environment: 84b0a1c1a6e1396a5aceb46ed2926b6da36e2e28 are a little off I think, the output folder should be /SCANsat/Plugins not /SCANsat.

It was intentional, for either:
1. my dev environment
   -  [ ] The target DLL needs to be in the `${TargetDir}` for several things (including soft debugging), and moving it by changing TargetDir may prevent this and other things from working. I need to verify if anything messes up here or not.
2. Possible bugs with the file location checking code:
   - [ ] It seems to have an `/n` instead of an `\n` somehwere; at least, all of the output was on a single line
   - [ ] I was leaving this in to make sure that was fixed!
