### ISSUE TITLE
Feature: Display Scanner range on KSP map

### ISSUE THREAD

**Issue by timobleeker** [KSPModStewards/SCANsat#74]
I think it will be helpful to have some sort of visual indicator on the ksp mapview showing the max/min/optimal altitude of the selected scanner. I was thinking this could be implemented as a cone that projects from the vessel icon to the surface of the planet being scanned. 

I wouldn't mind working on this myself but would need some pointers in the right direction to get started.

**Comment by MOARdV** [comment]
A visual indicator in 3D is going to be hard to do - if the normal of the scanning object is not perpendicular to the viewing angle, the rendered cone may be difficult to interpret, assuming you're intending to have the range bands displayed as part of the cone.

Now, if the cone is color coded, say "green" for "in optimum range", "yellow" for "inefficient because it's too low", and "red" for "too high", then I could see it working (alternatively, drawing a line from the scanning vessel towards the center of the planet, and color coding it as above would work, and be less coding effort).

**Comment by technogeeky** [comment]
> Now, if the cone is color coded, say "green" for "in optimum range", "yellow" for "inefficient because it's too low", and "red" for "too high", then I could see it working (alternatively, drawing a line from the scanning vessel towards the center of the planet, and color coding it as above would work, and be less coding effort).

Yes. So far, we do not do any orientation checking with any SCANsat parts, as far as I know. So the only sensible choice would be to project off of the vessel itself.

Does the OP propose to do this in the **Flight** view or the **Map** view?

**Comment by timobleeker** [comment]
I agree that this visual indicator should be projected from the vessel itself, not the scanner. I'd say this is most useful in the **map** view.

To start, this could even just be a line from the vessel to the planet, color coded to indicate optimal altitude, and possibly a circle projected on the planet from where the line hits the planet to indicate scanning surface.

**Comment by dtoxic47** [comment]
nice idea...but maybe there is an easier way still say green yellow red light alert? a small light on the scanner or as a separate part it would go green when the altitude is optimal ,yellow and red etc 
and maybe thats an even easier to code?! but then again what do i know about coding :D

**Comment by DMagic1** [comment]
Partially implemented in version 14 - #153  ; some kind of color indicator needs to be added; but this really only works for one scanner at a time. Multiple scanners on the same vessel will have a different field of view and different scanning status.
