### ISSUE TITLE
display Kethane data on map

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#8]
This is probably too generic, but:
- (**brienne**) suggests that we put Kethane data onto the Big Map, and that "it should not be handled by SCANsat itself" -- a principle we agree with.

I presume this will be expanded out to something generic:
- support _arbitrary resource location/density overlay_ on Big Map, with a system to handle them from various mods.
  - this may involve abstracting over the resources ourselves, and asking the other mod authors to report using our system
  - or there may be enough uniformity that we can just treat them as identical internally
  - but we certainly do not want to depend on every single mod for which we are _just_ rendering a bit of information about

**Comment by DMagic1** [comment]
The nice thing about ORS resources is that they have no persistent scanning record and no way of displaying the resource distribution. This means there is no need to sync up SCANsat data with any existing database. Kethane resources are considerable more complicated because of this.

I should also note that the system I've come up with so far (in the resource overlay branch) works fantastically. There is essentially no performance penalty for rendering the overlay and switching between resource types works well. The only real problem is some unexplained unevenness and spottiness in the scanning coverage using resource scanners.

Storing resource scanning data in the persistent file works well too. I just created an extra byte array, so every planet now has two.

**Comment by technogeeky** [comment]
This issue has been subsumed by a more generic system contributed by DMagic.

See [this issue](https://github.com/S-C-A-N/SCANsat/pull/36).
